### ISSUE TITLE
Unknown enum attribute

### ISSUE THREAD

**Issue by ryanb** [wallaby-rails/wallaby-rails#213]
Rails 7.1 introduced a change which requires an attribute exists when specifying `enum` in a model. Otherwise it raises `Unknown enum attribute` error. This means it's important that migrations don't load the model when they run, otherwise it will raise this error and you won't be able to generate the column to resolve it.

This normally isn't an issue but Wallaby loads models before migrations are run. Is there a way to bypass Wallaby eager loading when running migrations?

Actually might be nice to bypass the custom loading behavior for all cases because it seems to be a common source of issues. If the reason Wallaby eager loads models is so it knows which models exist, I'd much prefer manually managing a list of models for Wallaby so we can use Rails normal loading logic.

Update: Another issue with preloading is when setting up the app on a new machine, the `rails db:create` command doesn't work since Wallaby tries to load the models which depends on the database existing. It's not hard to create it outside of this command, just another hiccup.

@tian-im

**Comment by tian-im** [comment]
@ryanb Sorry for the late reply. I've added the patch to 0.2.10, could you try to upgrade `wallaby-core` to `0.2.10` and see if it fixes this issue?

This is the PR https://github.com/wallaby-rails/wallaby-core/pull/83 to suppress the preloading untill `/admin/*` is visited.

Let me know how you'd go.

BTW, Happy New Year!

**Comment by tian-im** [comment]
If it's still not working, I will add an option to disable the auto-detection.

**Comment by ryanb** [comment]
This works great, thanks @tian-im!

**Comment by ryanb** [comment]
@tian-im oops, spoke too soon. Some tests are failing because the decorator isn't loading with wallaby-core 0.2.10, it works in 0.2.9.

> undefined method `intercom_url' for #<SupportAdmin::ApplicationDecorator:0x00007f00416732a...

These are system/feature specs with capybara. It seems to work when testing manually in the browser.

From what I can tell, while in test env the development/eager_loading check is false so it never calls `pending!` and therefore never loads.

**Comment by ryanb** [comment]
@tian-im any chance you can take a look at the above issue? Would like to get this in place.

**Comment by tian-im** [comment]
@ryanb Sure, I will see how I can fix this. In the meantime, can you give me a minimal setup so that I can reproduce this in the system specs?

I've done the fix in the `main` and have system specs in there, but it doesn't seem to have similar issues.

**Comment by ryanb** [comment]
@tian-im it may be easier for me to submit a PR for this than recreate it in a sample Rails app. I'll try to look into this soon.

Just so I understand the code better, this condition basically excludes test environment, is there a reason? https://github.com/wallaby-rails/wallaby-core/blob/0.2-stable/lib/wallaby/engine.rb#L10

```rb
if Rails.env.development? || Rails.configuration.eager_load
```

**Comment by ryanb** [comment]
@tian-im I'm pretty sure the issue is here. https://github.com/wallaby-rails/wallaby-core/blob/0.2-stable/lib/wallaby/engine.rb#L25-L28

This basically only runs in test environment and it calls `require_all` but `pending` is never set so it doesn't do anything. If we add `pending!` call before `require_all` I believe that will fix it. I can do some testing tomorrow.

**Update**: I just did some testing and adding the `pending!` call before `require_all` fixes my issue. I also tried removing the `require_all` call after that and it also works. So it appears we can just call `pending!` which may lead to better performance on running tests that don't use Wallaby.

**Comment by tian-im** [comment]
> @tian-im it may be easier for me to submit a PR for this than recreate it in a sample Rails app. I'll try to look into this soon.
> 
> Just so I understand the code better, this condition basically excludes test environment, is there a reason? https://github.com/wallaby-rails/wallaby-core/blob/0.2-stable/lib/wallaby/engine.rb#L10
> 
> ```ruby
> if Rails.env.development? || Rails.configuration.eager_load
> ```

I think usually test environment caches the classes, so it won't hit the block a second time and that's why it's excluded.

I'm wondering if your test environment is set not to cache classes and reset classes in each suite or spec?

Maybe I should change to check if `config.cache_class` is `false` or not

**Comment by tian-im** [comment]
@ryanb could you give this pull request https://github.com/wallaby-rails/wallaby-core/pull/85 a try and see if it fixes the test issues? e.g.:

```ruby
# Gemfile
git 'https://github.com/wallaby-rails/wallaby-core.git', branch: 'fix/change-to-clear-instead-of-pending'
```

**Comment by ryanb** [comment]
@tian-im yes, that PR works in both development and test environments.

**Comment by tian-im** [comment]
@ryanb the PR is merged and `0.2.11` is released, could you give it a go and let me know if it works for you? Cheers!

**Comment by ryanb** [comment]
Works great, thanks @tian-im! I really appreciate you working on this.

**Comment by tian-im** [comment]
@ryanb `wallaby-7.0.0.beta2` is released. If you are interested, could you give it a try and see if it works for you or if you have any feedback?

Here are the changelogs:
- https://github.com/wallaby-rails/wallaby/blob/main/CHANGELOG.md
- https://github.com/wallaby-rails/wallaby-core/blob/main/CHANGELOG.md
- https://github.com/wallaby-rails/wallaby-active_record/blob/main/CHANGELOG.md

There are a few breaking changes, but you should see the instructions for fixing them.

The major breaking change is that a lot of the configuration in wallaby initializer is moved to `Admin::ApplicationController`.

There are a lot of improvements, here are some of the highlights:

- It uses `esbuild` and `scss-bundle` npm packages to compile the assets instead of using assets gems. Therefore, it should help to cut off quite a few dependencies. Otherwise, it doesn't change how things work from the app's perspective.
- Be able to define custom routes, see example at https://github.com/wallaby-rails/wallaby-core/pull/29

I will try to update the document to keep things documented. Just before I can finish that, let me know if you have any questions.

Thanks for your patience!

**Comment by ryanb** [comment]
@tian-im working on the upgrade and having an issue here: https://github.com/wallaby-rails/wallaby/issues/216

> It uses esbuild and scss-bundle npm packages to compile the assets instead of using assets gems. Therefore, it should help to cut off quite a few dependencies. Otherwise, it doesn't change how things work from the app's perspective

Nice! Glad to see this and the routing changes.
